load df:

In [2]:
import pandas as pd

#load data from TSV

df = pd.read_csv('tsv/test.tsv', delimiter='\t')

display(df)

,Measure,Local Onset,Global Onset,Duration,Pitch,MIDI
0,1,0.0,0.0,8.0,G3,55
1,1,8.0,8.0,4.0,F3,53
2,2,0.0,12.0,8.0,G4,67
3,2,0.0,12.0,3.0,G3,55
4,2,3.0,15.0,1.0,A3,57
...,...,...,...,...,...,...
792,63,11.0,667.0,1.0,E4,64
793,64,0.0,668.0,12.0,G4,67
794,64,0.0,668.0,12.0,D4,62
795,64,0.0,668.0,12.0,G3,55


In [5]:
# Binary conversion and visualization (refactored to py_scripts)
import numpy as np
import pandas as pd
from py_scripts.music_utils import create_binary_matrix, plot_binary_matrix

# Configuration
BINARY_RESOLUTION_METHOD = 'auto'   # 'auto' | 'manual' | 'standard'
BINARY_MANUAL_RES = None            # e.g., 0.5 when using 'manual'
Y_AXIS_MODE = 'full'              # 'full' | 'minmax' | 'chroma'
Y_AXIS_MIN = None                   # optional int when Y_AXIS_MODE=='minmax'
Y_AXIS_MAX = None                   # optional int when Y_AXIS_MODE=='minmax'

PLOTTING_BACKEND = 'bokeh'  # 'plt' | 'bokeh' | 'none'

# Build binary matrix
binary_matrix_df, meta = create_binary_matrix(
    df,
    resolution_method=BINARY_RESOLUTION_METHOD,
    manual_resolution=BINARY_MANUAL_RES,
    y_mode=Y_AXIS_MODE,
    midi_low=Y_AXIS_MIN,
    midi_high=Y_AXIS_MAX,
)

# Provide both orientations for convenience
binary_matrix_df_data = binary_matrix_df
binary_matrix_df_view = np.flipud(binary_matrix_df)

print(f"Binary matrix shape: {binary_matrix_df.shape}")
print(f"Resolution: {meta['resolution']}, columns: {meta['num_cols']}, y_mode: {meta['y_mode']}")

# Plot using the same backend as parsing cell (if defined), else default to 'plt'
backend_to_use = PLOTTING_BACKEND

# If measure offsets were computed earlier, you can pass them here.
# In this notebook, measure offsets are inside `results` items if needed; we default to None
plot_binary_matrix(
    binary_matrix_df,
    meta,
    backend=backend_to_use,
    measure_offsets=None,
    show_measure_lines=True,
    show=True,
)

Binary matrix shape: (128, 1360)
Resolution: 0.5, columns: 1360, y_mode: full


figure(id='p1001', ...)

In [6]:
print(binary_matrix_df_view)
print(binary_matrix_df_data)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
